web:
  container_name: gitlab
  image: 'gitlab/gitlab-ce:13.10.2-ce.0'
  restart: always
  hostname: 'gitlab.domain.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.domain.com'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = 'smtp.gmail.com'
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = 'username@domain.com'
      gitlab_rails['smtp_password'] = 'PASSWORD'
      gitlab_rails['smtp_domain'] = 'smtp.gmail.com'
      gitlab_rails['smtp_authentication'] = 'login'
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'none'
      gitlab_rails['gitlab_email_from'] = 'gitlab@domain.com'
      gitlab_rails['gitlab_email_reply_to'] = 'noreply@domain.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 2443
      gitlab_rails['time_zone'] = 'Asia/Kuala_Lumpur'
  ports:
    - '80:80'
    - '443:443'
    - '2443:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
