version: "3.8"
services:
    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - backend

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: [PASSWORD]
            MYSQL_DATABASE: [DATABASE]
            MYSQL_USER: [USERNAME]
            MYSQL_PASSWORD: [PASSWORD]
        networks:
            - backend

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - backend

networks:
    backend:
        driver: bridge
        name: my_app_net
